// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyFpLVHUNHr4DseiDrhX_A0tZRGZFI-DA',
    appId: '1:1008359661534:web:e1811002dc57b01348474f',
    messagingSenderId: '1008359661534',
    projectId: 'gamesapp-43afc',
    authDomain: 'gamesapp-43afc.firebaseapp.com',
    storageBucket: 'gamesapp-43afc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2wMp1Qxr0LogJmqXEt8MbY4wxN6p9rY',
    appId: '1:1008359661534:android:9150a3c2add0df4748474f',
    messagingSenderId: '1008359661534',
    projectId: 'gamesapp-43afc',
    storageBucket: 'gamesapp-43afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7C-9GAkNZZg62VrvZ9TxeUEsL1X7yWbI',
    appId: '1:1008359661534:ios:1aa8351b9fb768e748474f',
    messagingSenderId: '1008359661534',
    projectId: 'gamesapp-43afc',
    storageBucket: 'gamesapp-43afc.firebasestorage.app',
    iosBundleId: 'com.example.games',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7C-9GAkNZZg62VrvZ9TxeUEsL1X7yWbI',
    appId: '1:1008359661534:ios:1aa8351b9fb768e748474f',
    messagingSenderId: '1008359661534',
    projectId: 'gamesapp-43afc',
    storageBucket: 'gamesapp-43afc.firebasestorage.app',
    iosBundleId: 'com.example.games',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyFpLVHUNHr4DseiDrhX_A0tZRGZFI-DA',
    appId: '1:1008359661534:web:d7319c7554686d8648474f',
    messagingSenderId: '1008359661534',
    projectId: 'gamesapp-43afc',
    authDomain: 'gamesapp-43afc.firebaseapp.com',
    storageBucket: 'gamesapp-43afc.firebasestorage.app',
  );
}
